$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: experiment_env
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../../data-science/environment/experiment_env.yml
description: Environment created from a Docker image plus Conda environment to train a model.
