name: main

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  register-environment:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}    
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/experiment_env.yml
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
  register-dataset:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: seeds
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
      
  run-pipeline:
      needs: [get-config,register-environment,register-dataset]
      uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
        parameters-file:  mlops/azureml/train/pipeline.yml
        job-name: test
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
